// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChz4C8jDrtOe3pyr1F3wP5VWSZlzsiBw8',
    appId: '1:145222560729:web:e61fe14cf2ddf3a3d547c8',
    messagingSenderId: '145222560729',
    projectId: 'employee-management-app-83280',
    authDomain: 'employee-management-app-83280.firebaseapp.com',
    storageBucket: 'employee-management-app-83280.appspot.com',
    measurementId: 'G-ER03M3F85H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW9ZF-vSNE4FAcThtg_IZ9QqsAI5rBEM',
    appId: '1:145222560729:android:97f823a133c3a49bd547c8',
    messagingSenderId: '145222560729',
    projectId: 'employee-management-app-83280',
    storageBucket: 'employee-management-app-83280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQ_dtqVmG0NtbgRHAyFd-WNLU9fJ0zQY',
    appId: '1:145222560729:ios:280185df6bdc3019d547c8',
    messagingSenderId: '145222560729',
    projectId: 'employee-management-app-83280',
    storageBucket: 'employee-management-app-83280.appspot.com',
    iosBundleId: 'com.example.employeeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQ_dtqVmG0NtbgRHAyFd-WNLU9fJ0zQY',
    appId: '1:145222560729:ios:280185df6bdc3019d547c8',
    messagingSenderId: '145222560729',
    projectId: 'employee-management-app-83280',
    storageBucket: 'employee-management-app-83280.appspot.com',
    iosBundleId: 'com.example.employeeManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChz4C8jDrtOe3pyr1F3wP5VWSZlzsiBw8',
    appId: '1:145222560729:web:1a7bc8a92d157af7d547c8',
    messagingSenderId: '145222560729',
    projectId: 'employee-management-app-83280',
    authDomain: 'employee-management-app-83280.firebaseapp.com',
    storageBucket: 'employee-management-app-83280.appspot.com',
    measurementId: 'G-STE7NFT2YM',
  );
}
